config/routes.rb
ProjectsMgr::Application.routes.draw do
  resources :work_orders

  resources :project_phases

  resources :projects

  resources :users

  resources :positions

  get "home/index"

  root :to => 'home#index'

  match '/follower/project_associated_user_select_field/:project_id' => "follower#project_associated_user_select_field"
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :created, :created_by, :modified, :modified_by, :name, :remark
  validates :name, :presence => true,
                    :length => { :minimum => 2 }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, :notice => 'Position was successfully created.' }
        format.json { render :json => @position, :status => :created, :location => @position }
      else
        format.html { render :action => "new" }
        format.json { render :json => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, :notice => 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_field :remark %>
  </div>
  <div class="field">
    <%= f.label :created %><br />
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :modified %><br />
    <%= f.datetime_select :modified %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :modified_by %><br />
    <%= f.text_field :modified_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Remark</th>
    <th>Created</th>
    <th>Modified</th>
    <th>Created by</th>
    <th>Modified by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.name %></td>
    <td><%= position.remark %></td>
    <td><%= position.created %></td>
    <td><%= position.modified %></td>
    <td><%= position.created_by %></td>
    <td><%= position.modified_by %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @position.name %>
</p>

<p>
  <b>Remark:</b>
  <%= @position.remark %>
</p>

<p>
  <b>Created:</b>
  <%= @position.created %>
</p>

<p>
  <b>Modified:</b>
  <%= @position.modified %>
</p>

<p>
  <b>Created by:</b>
  <%= @position.created_by %>
</p>

<p>
  <b>Modified by:</b>
  <%= @position.modified_by %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>