config/routes.rb
ProjectsMgr::Application.routes.draw do
  resources :work_orders

  resources :project_phases

  resources :projects

  resources :users

  resources :positions

  get "home/index"

  root :to => 'home#index'

  match '/follower/project_associated_user_select_field/:project_id' => "follower#project_associated_user_select_field"
end

app/models/work_order.rb
# -*- coding: utf-8 -*-
STATUS_NEW = 1
STATUS_DEVEL = 2
STATUS_TEST = 3
STATUS_DONE = 4

# TODO
# 更新和删除的时候没有同时更新，相关数据的总工作时间
class WorkOrder < ActiveRecord::Base
  belongs_to :project_phase
  belongs_to :project
  belongs_to :user
  belongs_to :follower

  attr_accessible :content, :created, :remark, :status, :work_hours,
                  :project_phase_id, :project_id, :user_id, :follower_id
  validates :content, :created, :work_hours, :project_phase_id, :user_id, :presence => true

  before_save do |work_order|
    if work_order.respond_to? "status" \
      or work_order.status.nil \
      or work_order.status.empty \
      or [STATUS_, STATUS_DEVEL, STATUS_TEST, STATUS_DONE].find_index(work_order.status).nil
      work_order.status = STATUS_NEW
    end
    work_order.project_id = ProjectPhase.find(work_order.project_phase_id).project_id
    work_order.follower_id = Follower.where('project_id=? and user_id=?', work_order.project_id, work_order.user_id).first.id
  end

  after_update do |work_order|
    if work_order.status == STATUS_DONE
      add_associated_data_work_hours(work_order)
    end
  end

  after_destroy do |work_order|
    if work_order.status == STATUS_DONE
      sub_associated_data_work_hours(work_order)
    end
  end

  def add_associated_data_work_hours(work_order)
    work_hours = work_order.work_hours
    work_order.project_phase.total_work_hours += work_hours
    work_order.project.total_work_hours += work_hours
    work_order.user.total_work_hours += work_hours
    work_order.follower.work_hours += work_hours

    work_order.project_phase.save
    work_order.project.save
    work_order.user.save
    work_order.follower.save
  end

  def sub_associated_data_work_hours(work_order)
    work_hours = work_order.work_hours
    work_order.project_phase.total_work_hours -= work_hours
    work_order.project.total_work_hours -= work_hours
    work_order.user.total_work_hours -= work_hours
    work_order.follower.work_hours -= work_hours

    work_order.project_phase.save
    work_order.project.save
    work_order.user.save
    work_order.follower.save
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  # GET /work_orders
  # GET /work_orders.json
  def index
    @work_orders = WorkOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @work_orders }
    end
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @work_order }
    end
  end

  # GET /work_orders/new
  # GET /work_orders/new.json
  def new
    @work_order = WorkOrder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @work_order }
    end
  end

  # GET /work_orders/1/edit
  def edit
    @work_order = WorkOrder.find(params[:id])
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = WorkOrder.new(params[:work_order])

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, :notice => 'Work order was successfully created.' }
        format.json { render :json => @work_order, :status => :created, :location => @work_order }
      else
        format.html { render :action => "new" }
        format.json { render :json => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_orders/1
  # PUT /work_orders/1.json
  def update
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      if @work_order.update_attributes(params[:work_order])
        format.html { redirect_to @work_order, :notice => 'Work order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order = WorkOrder.find(params[:id])
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to work_orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.erb
<% content_for :header do %>
<%= javascript_include_tag "work_orders_form" %>
<% end %>
<div class="form block">
  <%= form_for(@work_order) do |f| %>
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fieldset">
    <div class="field">
      <div class="label"><%= f.label :content %></div>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <div class="label"><%= f.label :remark %></div>
      <%= f.text_area :remark %>
    </div>
    <div class="field">
      <div class="label"><%= f.label :work_hours %></div>
      <%= f.number_field :work_hours %>
    </div>
    <div class="field">
      <div class="label"><%= f.label :created %></div>
      <%= f.datetime_select :created %>
    </div>
    <div class="field">
      <div class="label"><%= f.label :project_phase %></div>
      <%= f.select :project_phase_id, [['Please select', '']] |
                                      ProjectPhase.all.collect { |project_phase| [project_phase.project.name + "-" + project_phase.name, project_phase.id] } %>
    </div>
    <div id="user_select_field_container">

    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>
</div>

app/views/work_orders/edit.html.erb
<div class="edit-wrapper">
  <div class="block-header">
    <div><h4>Editing work_order</h4></div>
    <div class="split-line"></div>
  </div>
  <%= render 'form' %>
  <%= link_to 'Show', @work_order %> |
  <%= link_to 'Back', work_orders_path %>
</div>

app/views/work_orders/index.html.erb
<% content_for :header do %>
<%= javascript_include_tag "jquery_vtgrid" %>
<% end %>
<div class="list-wrapper">
  <div class="grid block">
    <div class="block-header">
      <div><h4>Listing work orders</h4></div>
      <div class="split-line"></div>
    </div>
    <table>
      <thead>
        <tr class="headings">
          <th>Content</th>
          <th>Remark</th>
          <th>Status</th>
          <th>Work hours</th>
          <th>Created</th>
          <th>Project phase</th>
          <th>Project</th>
          <th>User</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @work_orders.each_with_index do |work_order, index| %>
        <tr <% if index%2==0 %>class="even pointer"<% else %>class="pointer"<% end %>>
          <td><%= work_order.content %></td>
          <td><%= work_order.remark %></td>
          <td><%= work_order.status %></td>
          <td><%= work_order.work_hours %></td>
          <td><%= work_order.created %></td>
          <td><%= work_order.project_phase.name %></td>
          <td><%= work_order.project.name %></td>
          <td><%= work_order.user.name %></td>
          <td><%= link_to 'Show', work_order %></td>
          <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
          <td><%= link_to 'Destroy', work_order, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="options">
      <ul class="">
        <li class="lf"><%= link_to 'New Work order', new_work_order_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/work_orders/new.html.erb
<div class="new-wrapper">
  <div class="block-header">
    <div><h4>New Work order</h4></div>
    <div class="split-line"></div>
  </div>
  <%= render 'form' %>
  <%= link_to 'Back', work_orders_path %>
</div>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @work_order.content %>
</p>

<p>
  <b>Remark:</b>
  <%= @work_order.remark %>
</p>

<p>
  <b>Status:</b>
  <%= @work_order.status %>
</p>

<p>
  <b>Work hours:</b>
  <%= @work_order.work_hours %>
</p>

<p>
  <b>Created:</b>
  <%= @work_order.created %>
</p>

<p>
  <b>Project phase:</b>
  <%= @work_order.project_phase %>
</p>


<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>